# Write SQL queries to perform the following tasks using the Sakila database:

    # 1. List the number of films per category.
    SELECT COUNT(film_id), category.name
    FROM film_category
    INNER JOIN category
    ON film_category.category_id = category.category_id
    GROUP BY category.name;
    
    # 2. Retrieve the store ID, city, and country for each store.
    
	SELECT store.store_id, city.city, country.country
	FROM store
	INNER JOIN address
	ON store.address_id = address.address_id
    INNER JOIN city
    ON address.city_id = city.city_id
    INNER JOIN country
    ON city.country_id = country.country_id;

	# 3. Calculate the total revenue generated by each store in dollars.
    SELECT SUM(payment.amount), store.store_id
    FROM payment
    INNER JOIN customer
    ON payment.customer_id = customer.customer_id
    INNER JOIN store
    ON customer.store_id = store.store_id
    GROUP BY store.store_id;
    
	# 4. Determine the average running time of films for each category.
    
    SELECT AVG(film.length), category.name
    FROM film_category
    INNER JOIN category
    ON film_category.category_id = category.category_id
    INNER JOIN film
    ON film_category.film_id = film.film_id
    GROUP BY category.name;