# Write SQL queries to perform the following tasks using the Sakila database:

    # 1. List the number of films per category.
    SELECT COUNT(film_id), category.name
    FROM film_category
    INNER JOIN category
    USING (category_id)
    GROUP BY category.name;
    
    # 2. Retrieve the store ID, city, and country for each store.
    
	SELECT store.store_id, city.city, country.country
	FROM store
	INNER JOIN address
	USING (address_id)
    INNER JOIN city
    USING (city_id)
    INNER JOIN country
    USING (country_id);

	# 3. Calculate the total revenue generated by each store in dollars.
    SELECT SUM(payment.amount), store.store_id
    FROM payment
    INNER JOIN customer
    USING (customer_id)
    INNER JOIN store
    USING (store_id)
    GROUP BY store.store_id;
    
	# 4. Determine the average running time of films for each category.
    
    SELECT AVG(film.length), category.name
    FROM film_category
    INNER JOIN category
    USING (category_id)
    INNER JOIN film
    USING (film_id)
    GROUP BY category.name;